on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: restore timestamps
      uses: chetan/git-restore-mtime-action@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzrP --delete --exclude=".git*/"
        path: ./
        remote_path: /home/customer/www/akvm.com/public_html/wp-content/themes/akvm
        remote_host: gtxm1172.siteground.biz
        remote_port: 18765
        remote_user: u2462-a96zxysljtky
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
